version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 3s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: makafonov/foodgram:latest
    restart: always
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/media
