# Generated by Django 3.1.5 on 2021-01-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210121_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(choices=[('green', 'Завтрак'), ('orange', 'Обед'), ('purple', 'Ужин')], default='orange', max_length=10, unique=True, verbose_name='Описание'),
        ),
    ]
